# Generated by Django 3.2 on 2023-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
# from movie_app.models import Movie
